name: Patch APK and Upload Artifact

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter APK URL'
        required: true
      version:
        description: 'Enter the version number:'
        required: true

jobs:
  patch-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'  # Change this to your required Java version

      - name: Download IGExperimentsPatcher
        run: |
          wget --show-progress -q --progress=bar:force:noscroll https://github.com/xHookman/IGExperimentsPatcher/releases/download/1.0/IGExperimentsPatcher.jar -O IGExperimentsPatcher.jar

      - name: Download APK
        run: |
          wget --show-progress -q --progress=bar:force:noscroll "${{ inputs.name }}" -O "${{ inputs.version }}".apk
          
      - name: Patch APK
        run: java -jar IGExperimentsPatcher.jar ${{ inputs.version }}.apk

      - name: Download uber-apk-signer
        run: |
          wget --show-progress -q --progress=bar:force:noscroll https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar -O uber-apk-signer.jar

      - name: Sign Patched
        run: java -jar uber-apk-signer.jar -a ${{ inputs.version }}-patched.apk
      
      - name: Find APKs
        run: |
          apk_files=$(find . -type f -name '*.apk')
          echo "Found APK files: $apk_files"
      
      - name: Upload signed Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.version }}
          path: ${{ inputs.version }}-patched-aligned-debugSigned.apk  # Change this to the actual patched APK path

      - name: Get Artifact URL
        id: get_url
        run: echo "::set-output name=url::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        env:
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}

      - name: Print Artifact URL
        run: echo "Artifact URL: ${{ steps.get_url.outputs.url }}"
