name: Patch APK and Upload Artifact

on: workflow_dispatch

jobs:
  patch-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'  # Change this to your required Java version

      - name: Download IGExperimentsPatcher
        run: |
          wget https://github.com/xHookman/IGExperimentsPatcher/releases/download/1.0/IGExperimentsPatcher.jar -O IGExperimentsPatcher.jar

      - name: Download APK
        run: |
          wget https://dl.NoGutsNoGlory.eu.org/289867/com_instagram_android_308_0_0_0_71_370805265_minAPI28_arm64_v8a.apk?hash=fzmdJ7r -O igarm64v8.apk
          
      - name: Patch APK
        run: java -jar IGExperimentsPatcher.jar igarm64v8.apk

      - name: Download uber-apk-signer
        run: |
          wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar -O uber-apk-signer.jar

      - name: Sign Patched
        run: java -jar uber-apk-signer.jar -a igarm64v8.apk
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: patched-apk
          path: igarm64v8.apk  # Change this to the actual patched APK path

      - name: Find APKs
        run: |
          apk_files=$(find . -type f -name '*.apk')
          echo "Found APK files: $apk_files"
