name: Patch APK and Upload Artifact

on: workflow_dispatch

jobs:
  patch-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'  # Change this to your required Java version

      - name: Download IGExperimentsPatcher
        run: |
          wget https://github.com/xHookman/IGExperimentsPatcher/releases/download/1.0/IGExperimentsPatcher.jar -O IGExperimentsPatcher.jar

      - name: Download APK
        run: |
          wget https://dl.NoGutsNoGlory.eu.org/289861/com_instagram_android_300_0_0_0_60_370004451_minAPI28_arm64_v8a.apk?hash=vGpveBd -O igarm64v8.apk
          
      - name: Patch APK
        run: java -jar IGExperimentsPatcher.jar igarm64v8.apk

      - name: Find APKs
        run: |
          apk_files=$(find . -type f -name '*.apk')
          echo "Found APK files: $apk_files"
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: patched-apk
          path: igarm64v8.apk  # Change this to the actual patched APK path
